apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ody6pllsi-python
  janus-idp.io/tekton: ody6pllsi-python
  backstage.io/kubernetes-id: ody6pllsi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ody6pllsi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
