apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ody6pllsi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ody6pllsi-python 
  name: ody6pllsi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ody6pllsi-python 
